version: '3.8' 

services:

  frontend:
    build:
      context: ./frontend 
      dockerfile: Dockerfile 
    ports:
      - "8501:8501" 
    networks:
      - calorie-net 
    depends_on:
      - backend


  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile 
    container_name: backend-container 
    networks:
      - calorie-net 

networks:
  calorie-net:
    driver: bridge 